const mongoose = require("mongoose");

const entrySchema = new mongoose.Schema({
  name: { type: String },
  age: { type: String },
  address: { type: String },
  purpose: { type: String },
  appointmentDate: { type: String },
  createDate: { type: String },
  mobileNumber: { type: String },
  createdBy: { type: String },

  // Survey Questions
  q1: { type: String },
  q2: { type: String },
  q3: { type: String },
  q4: { type: String },
  q5: { type: String },
  q6: { type: String },
  q7: { type: String },
  q8: { type: String },
  q9a: { type: String },
  q9b: { type: String },
  q9c: { type: String },
  q9d: { type: String },
  q9e: { type: String },
  q9f: { type: String },
  q9g: { type: String },
  q9h: { type: String },
  q10: { type: String },
  q11: { type: String },
  q12: { type: String },
  q13: { type: String },
  q14: { type: String },
  q15: { type: String },
  q16: { type: String },
  q17: { type: String },
  q18: { type: String },
  q19: { type: String },
  q20: { type: String },
  q21: { type: String },
  q22: { type: String },
  q23: { type: String },
  q24: { type: String },
  q25: { type: String },
  q26: { type: String },
  q27: { type: String },
  q28: { type: String },
  q29: { type: String },
  q30: { type: String },
  q31: { type: String },
  q32: { type: String }
});

module.exports = mongoose.model("Entry", entrySchema);
